### ISSUE TITLE
Some questions which people looking forward to try this would like answers to.

### ISSUE THREAD

**Issue by samarth015** [Martazza/Huawei-Bootloader-Unlocker#13]
How long does it take generally? 
Does it work for all Huawei/Honor models ? 
How many devices have you tried this on and for how many did it work? 
Does this work for non american/european devices?

**Comment by Iey4iej3** [comment]
If you can read C codes, you will find that this is simply a loop to brute-force enumerate all possible unlock codes. It is claimed to be "fastest" probably because it is written in C (but I am quite skeptical: Rust codes often run [faster](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust.html) than C, say).
